package com.gaiaspa.metrics_detection.ml
import android.graphics.Bitmap

/**
 * Immutable result container returned by [MetricsPipeline.invokeFromFile].
 *
 * Aggregates all pipeline outputs: bounding-box detections, quantity/calibre
 * predictions, visual overlays, timing metadata, and the raw native JSON
 * payload for downstream consumers that need unparsed fields.
 *
 * @property preProcessTime Reserved for future use; currently always 0.
 * @property interfaceTime Inference wall-clock time reported by the native engine (milliseconds).
 * @property postProcessTime Reserved for future use; currently always 0.
 * @property results List of individual berry detection results (bounding boxes + class labels).
 * @property depthMap Reserved for depth-assisted inference; currently always null.
 * @property mmPerPx Reserved for future calibration; currently always 0.0.
 * @property predictsList Calibre/quantity prediction for each detection cluster (typically a single entry).
 * @property imageOrig Reserved; currently always null.
 * @property imagePro Pair of (visual_overlay, debug_overlay) bitmaps generated by native code.
 * @property rawJson The unmodified JSON string returned by the JNI bridge, useful for
 *        debugging or extracting fields not exposed in the typed model.
 */
data class Success(
    val preProcessTime: Long,
    val interfaceTime: Long,
    val postProcessTime: Long,
    val results: List<SegmentationResult>,
    val depthMap: Bitmap?,
    val mmPerPx: Float,
    val predictsList: List<com.gaiaspa.metrics_detection.data.model.CalPredict>,
    val imageOrig: Bitmap?,
    val imagePro: Pair<Bitmap?, Bitmap?>,
    val rawJson: String? = null
)
