# Ruta al keystore de release (local, no trackeado)
storeFile=/home/maxi/Escritorio/modelo_nuevo/optimizacion_uvas/keystores/key1.jks
storePassword=Maxi12345!
keyAlias=metrics_releasekey0
keyPassword=Maxi12345!
