package com.gaiaspa.metrics_detection.data.model

/**
 * Data model representing the caliber prediction result for a grape bunch.
 *
 * Each instance corresponds to a prediction from the backend or the local
 * engine. It is storable as JSON within the `cal_predicts` column of a [Lote]
 * via Room's [Converters].
 *
 * @property error Error message in case the prediction failed.
 * @property status `true` if the prediction was successful.
 * @property bunchColor Detected bunch color.
 * @property qty Estimated berry count for the bunch.
 * @property std Standard deviation of the caliber histogram.
 * @property mean Mean of the caliber histogram.
 * @property mode Mode of the caliber histogram.
 * @property pred Counts per histogram bin.
 * @property bins Histogram caliber bin boundaries.
 * @property fusionMetadata Multi-view fusion metadata, if the prediction was
 *                          generated by [FusionEngine].
 */
data class CalPredict(
    val error: String = "",
    val status: Boolean = false,
    val bunchColor: String = "",
    val qty: Int = 0,
    val std: Float = 0f,
    val mean: Float = 0f,
    val mode: Float = 0f,
    val pred: List<Int> = emptyList(),
    val bins: List<Float> = emptyList(),
    val fusionMetadata: FusionMetadata? = null
)
