package com.gaiaspa.metrics_detection.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey

/**
 * Room entity representing a grape caliber analysis lot.
 *
 * Stores both the images at each stage of the pipeline (source, normalized,
 * upload, overlay) and the prediction results ([CalPredict]) along with
 * backend synchronization flags.
 *
 * ## Image lifecycle
 * 1. `sourceImages` — raw device capture.
 * 2. `normalizedImages` — preprocessed for inference.
 * 3. `uploadImages` — clean versions uploaded to the backend.
 * 4. `overlayImages` — visual overlay generated by C++ with detection ovals.
 * 5. `cloudImages` — URLs/images returned by the backend after synchronization.
 *
 * ## Dynamic property `images`
 * The computed property [images] resolves in cascade which set to show
 * in the UI: prioritizes `overlayImages` > `uploadImages` > `normalizedImages` >
 * `sourceImages`. This way the user always sees the detections in the
 * history even if the overlay has not yet been generated.
 *
 * @property id Locally auto-generated primary key.
 * @property userId Identifier of the user who owns the lot.
 * @property cloudId Identifier assigned by the backend after successful synchronization.
 * @property company Company the lot belongs to.
 * @property vessel Vessel associated with the lot.
 * @property block Production block within the vessel.
 * @property varietyId Canonical variety identifier according to [RuntimeVarietyCatalog].
 * @property varietyName Variety name for UI display.
 * @property predictedAt Prediction timestamp (epoch millis).
 * @property createdAt Local creation timestamp (epoch millis).
 * @property updatedAt Last local modification timestamp (epoch millis).
 * @property sourceImages List of captured source image paths.
 * @property normalizedImages List of image paths normalized for ML.
 * @property uploadImages List of clean image paths ready for upload to the backend.
 * @property overlayImages List of image paths with C++ detection overlay.
 * @property cloudImages List of image paths/URLs from the backend.
 * @property calPredicts List of caliber predictions associated with the lot.
 * @property toDelete Logical deletion flag pending synchronization.
 * @property toUpdate Update flag pending synchronization.
 * @property synced `true` if the lot was successfully synchronized with the backend.
 * @property syncError Message of the last synchronization error, or `null` if successful.
 */
@Entity(tableName = "lote")
data class Lote(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,

    val userId: String,
    val cloudId: String = "",
    val company: String,
    val vessel: String,
    val block: String,

    val varietyId: Int = -1,
    val varietyName: String = "",

    val predictedAt: Long = System.currentTimeMillis(),
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "source_images")
    val sourceImages: List<String> = emptyList(),

    @ColumnInfo(name = "normalized_images") 
    val normalizedImages: List<String> = emptyList(),

    @ColumnInfo(name = "upload_images") 
    val uploadImages: List<String> = emptyList(), 

    @ColumnInfo(name = "overlay_images")
    val overlayImages: List<String> = emptyList(),

    @ColumnInfo(name = "cloudImages")
    val cloudImages: List<String> = emptyList(),

    @ColumnInfo(name = "cal_predicts")
    val calPredicts: List<CalPredict> = emptyList(),

    @ColumnInfo(name = "toDelete")
    val toDelete: Boolean = false,

    @ColumnInfo(name = "toUpdate")
    val toUpdate: Boolean = false,

    @ColumnInfo(name = "synced")
    val synced: Boolean = false,

    @ColumnInfo(name = "syncError")
    val syncError: String? = null
) {
    /**
     * Dynamic property for UI.
     * FIXED: Prioritizes overlayImages (res_ with native detection ovals)
     * so the user always sees the detections in the history.
     *
     * Cascade resolution guarantees that a set of images is always returned,
     * descending from the most informative (overlay) down to the raw capture.
     */
    @get:Ignore
    val images: List<String>
        get() = overlayImages.ifEmpty { uploadImages.ifEmpty { normalizedImages.ifEmpty { sourceImages } } }
}
